set_property PACKAGE_PIN G4 [get_ports {people_led[1]}]
set_property PACKAGE_PIN F6 [get_ports {people_led[0]}]
set_property PACKAGE_PIN K2 [get_ports {car_led[2]}]
set_property PACKAGE_PIN J3 [get_ports {car_led[1]}]
set_property PACKAGE_PIN J2 [get_ports {car_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {car_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {car_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {car_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {people_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {people_led[1]}]

set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN R11 [get_ports enable_in]
set_property PACKAGE_PIN U4 [get_ports rst]
set_property PACKAGE_PIN D5 [get_ports {dis[7]}]
set_property PACKAGE_PIN B2 [get_ports {dis[6]}]
set_property PACKAGE_PIN B3 [get_ports {dis[5]}]
set_property PACKAGE_PIN A1 [get_ports {dis[4]}]
set_property PACKAGE_PIN B1 [get_ports {dis[3]}]
set_property PACKAGE_PIN A3 [get_ports {dis[2]}]
set_property PACKAGE_PIN A4 [get_ports {dis[1]}]
set_property PACKAGE_PIN B4 [get_ports {dis[0]}]

set_property PACKAGE_PIN H2 [get_ports {dis_left[7]}]
set_property PACKAGE_PIN D2 [get_ports {dis_left[6]}]
set_property PACKAGE_PIN E2 [get_ports {dis_left[5]}]
set_property PACKAGE_PIN F3 [get_ports {dis_left[4]}]
set_property PACKAGE_PIN F4 [get_ports {dis_left[3]}]
set_property PACKAGE_PIN D3 [get_ports {dis_left[2]}]
set_property PACKAGE_PIN E3 [get_ports {dis_left[1]}]
set_property PACKAGE_PIN D4 [get_ports {dis_left[0]}]

set_property PACKAGE_PIN G2 [get_ports {sel[7]}]
set_property PACKAGE_PIN C2 [get_ports {sel[6]}]
set_property PACKAGE_PIN C1 [get_ports {sel[5]}]
set_property PACKAGE_PIN H1 [get_ports {sel[4]}]
set_property PACKAGE_PIN G1 [get_ports {sel[3]}]
set_property PACKAGE_PIN F1 [get_ports {sel[2]}]
set_property PACKAGE_PIN E1 [get_ports {sel[1]}]
set_property PACKAGE_PIN G6 [get_ports {sel[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {dis[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {dis_left[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis_left[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis_left[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis_left[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis_left[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis_left[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis_left[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis_left[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {sel[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports enable_in]
set_property IOSTANDARD LVCMOS33 [get_ports rst]





set_property PACKAGE_PIN D4 [get_ports {dis_right[0]}]
set_property PACKAGE_PIN E3 [get_ports {dis_right[1]}]
set_property PACKAGE_PIN D3 [get_ports {dis_right[2]}]
set_property PACKAGE_PIN F4 [get_ports {dis_right[3]}]
set_property PACKAGE_PIN F3 [get_ports {dis_right[4]}]
set_property PACKAGE_PIN E2 [get_ports {dis_right[5]}]
set_property PACKAGE_PIN D2 [get_ports {dis_right[6]}]
set_property PACKAGE_PIN H2 [get_ports {dis_right[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis_right[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis_right[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis_right[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis_right[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis_right[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis_right[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis_right[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis_right[0]}]
